/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressInfo: typeof import('./src/components/Checkout/AddressInfo.vue')['default']
    DistrictSelector: typeof import('./src/components/Checkout/DistrictSelector.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    GoodsItemDetail: typeof import('./src/components/Detail/GoodsItemDetail.vue')['default']
    GoodsItemSku: typeof import('./src/components/Detail/GoodsItemSku.vue')['default']
    HomeBanner: typeof import('./src/components/Home/HomeBanner.vue')['default']
    HomeCategory: typeof import('./src/components/Home/HomeCategory.vue')['default']
    HomeHot: typeof import('./src/components/Home/HomeHot.vue')['default']
    HomeNew: typeof import('./src/components/Home/HomeNew.vue')['default']
    HomePanel: typeof import('./src/components/Home/HomePanel.vue')['default']
    HomeProduct: typeof import('./src/components/Home/HomeProduct.vue')['default']
    HotList: typeof import('./src/components/Detail/HotList.vue')['default']
    LayoutCart: typeof import('./src/components/Layout/LayoutCart.vue')['default']
    LayoutFoot: typeof import('./src/components/Layout/LayoutFoot.vue')['default']
    LayoutHeader: typeof import('./src/components/Layout/LayoutHeader.vue')['default']
    LayoutNav: typeof import('./src/components/Layout/LayoutNav.vue')['default']
    OrderList: typeof import('./src/components/Order/OrderList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondBanner: typeof import('./src/components/SecondCategory/SecondBanner.vue')['default']
    SecondCategory: typeof import('./src/components/SecondCategory/SecondCategory.vue')['default']
    SubGoods: typeof import('./src/components/Sub/SubGoods.vue')['default']
  }
  export interface GlobalDirectives {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
